### PR TITLE
Full imports

### PR DESCRIPTION
**Pull request by ExaneServerTeam**
Hello

I tried your sphinx extension with VScode + RestructuredText pluggin.
The plugin embed esbonio for restructured text lsp & rendering.
-> Activating your module breaks esbonio
-> This fix your sphinx extension usage within this environment

### CODE REVIEW

**Comment by kkAyataka** [comment]
v1.1.0 was broken. I have fixed it and released v1.1.1. Has this issue been resolved as well?

**Comment by ExaneServerTeam** [comment]
Hello I confirm it is fixed on my end with the v1.1.1 release.
You can cancel my pull request ;)

**Comment by ExaneServerTeam** [comment]
Sorry for the bad news but it looks broken on my end.

`
C:\cygwin64\home\brin_f\Devel\doc\BNPP>make clean && make confluence
Removing everything under '_build'...
Running Sphinx v5.3.0

Extension error:
Could not import extension sphinxcontrib.xlsxtable (exception: No module named 'xlsxtable')
`

**Comment by ExaneServerTeam** [comment]
Forget about my previous comment. With the the right sphinx version, it is working fine.

**Pull request closed without merging**
